/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leetcode;

/**
 * Find the Difference
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more 
 * letter at a random position.
 * Find the letter that was added in t.
 * 
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 * 
 * @author Johnny
 */
public class Solution389 {
    public char findTheDifference(String s, String t) {
        return 'a';
    }
    
}
