#Create MySQL Image for JSP Tutorial Application
#docker build -t leetcodemysql:0.1 .
#docker run --detach --name=leetcodemysql --publish 6603:3306 leetcodemysql:0.1

FROM mysql
MAINTAINER jojozhuang@gmail.com

ENV MYSQL_ROOT_PASSWORD leetcode

EXPOSE 3306
