package johnny.leetcode.algorithm;

/**
 * Find the Difference
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more 
 * letter at a random position.
 * Find the letter that was added in t.
 * 
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 * 
 * @author Johnny
 */
public class Solution389 {
    public char findTheDifference(String s, String t) {
        if (s == null || t == null || t.isEmpty() ||
            s.length() != t.length() - 1) {
            return ' ';
        }
        
        // Appearance times for each letter
        int[] countArray = new int[26];
        
        for (int i = 0; i < s.length(); i++) {
            countArray[s.charAt(i) - 'a']++;
        }
        
        for (int i = 0; i < t.length(); i++) {
            countArray[t.charAt(i) - 'a']--;
        }
        
        for (int i = 0; i < countArray.length; i++) {
            if (countArray[i] != 0) {
                return (char)('a' + i);
            }
        }
        
        return ' ';
    }
    
}
